classdef aten__slice0 < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %aten__slice0 Auto-generated custom layer
    % Auto-generated by MATLAB on 08-Jun-2025 22:01:30
    
    properties (Learnable)
        % Networks (type dlnetwork)
        
    end
    
    properties
        % Non-Trainable Parameters
        slice_9
        slice_91
        slice_10
        slice_14
        
        
        
    end
    
    properties (Learnable)
        % Trainable Parameters
        
    end
    
    methods
        function obj = aten__slice0(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 2;
            obj.NumOutputs = 2;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end
        
        function [slice_12, slice_12_rank] = predict(obj,slice_8, slice_8_rank)
            
            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [slice_8, slice_8_format] = maglev_rnn_traced.ops.permuteToReversePyTorch(slice_8, '', numel(slice_8_rank));
            [slice_8] = struct('value', slice_8, 'rank', int64(numel(slice_8_rank)));
            
            [slice_12] = tracedPyTorchFunction(obj,slice_8,false,"predict");
            
            [slice_12_rank] = ones([1,slice_12.rank], 'single');
            slice_12_rank = dlarray(slice_12_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(slice_12.value) == 'U'))
                slice_12 = permute(slice_12.value, fliplr(1:max(2,slice_12.rank)));
            end
            
        end
        
        
        
        function [slice_12, slice_12_rank] = forward(obj,slice_8, slice_8_rank)
            
            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [slice_8, slice_8_format] = maglev_rnn_traced.ops.permuteToReversePyTorch(slice_8, '', numel(slice_8_rank));
            [slice_8] = struct('value', slice_8, 'rank', int64(numel(slice_8_rank)));
            
            [slice_12] = tracedPyTorchFunction(obj,slice_8,true,"forward");
            
            [slice_12_rank] = ones([1,slice_12.rank], 'single');
            slice_12_rank = dlarray(slice_12_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(slice_12.value) == 'U'))
                slice_12 = permute(slice_12.value, fliplr(1:max(2,slice_12.rank)));
            end
            
        end
        
        
        
        function [slice_12] = tracedPyTorchFunction(obj,slice_8,isForward,predict)
            
            [slice_9] = maglev_rnn_traced.ops.makeStructForConstant(int64(obj.slice_9), int64(0), "Typed");
            [slice_91] = maglev_rnn_traced.ops.makeStructForConstant(int64(obj.slice_91), int64(0), "Typed");
            [slice_10] = maglev_rnn_traced.ops.makeStructForConstant(int64(obj.slice_10), int64(0), "Typed");
            [slice_14] = maglev_rnn_traced.ops.makeStructForConstant(int64(obj.slice_14), int64(0), "Typed");
            [slice_12] = maglev_rnn_traced.ops.pySlice(slice_8, slice_9, slice_91, slice_10, slice_14, false);
        end
        
    end
end

